# main text of home
name: Lauren Pisano Yoga
bio: '<p>When we approach the practice as a creative expression, we are artists. We ignite the fire of creativity within ourselves and experience the teachings as they are; living, impermanent and ceaselessly transforming.</p>
<p>When we approach the practice as a discipline, we are held in the sacred tradition of yoga. We learn humility. We learn reverence. We learn what it means to be grounded.</p>
<p>My practice (and therefore, teaching) is a dance around this balance point between discipline and artistry. I offer what wisdom has been revealed to me in my journey, as it is natural and relevant to the moment I share with you in the yoga room. Classes are flowing, grounded and deliberate.</p>
<p>Adi Vajra and Stephanie Adams showed me what yoga is. My teaching is a tree grown in their soil.</p>
<p>Join or connect with me as it serves you. All are welcome. It is not important that you are perfect, only that you are sincere.</p>
<p>Yours truly, eternally in bloom,<br>
Lauren</p>'

# if it's an external image, update below for true
external-image: false
picture: 'assets/images/lauren_headshot.jpg'

retreats:
  -
    title: 'Stay tuned...'
  # -
    # title: 'Yoga Philosophy in Practice, Yoga Flow SF Ocean, San Francisco, CA'
    # date: 'Wed July 13, 20 and 27, 2016 at 6:30pm'
    # description: 'An open, interactive, thought-provoking discussion of yogic philosophy centered on the Yamas, Niyamas and Kleshas of Patanjali’s Yoga Sutras. These teachings are at the core of our yoga practice and can widen our perspective of life, self and relationships. We will have thoughtful discourse on the teachings and discuss how these concepts show up in our lives. No prior knowledge is needed. Learn more and sign up at <a href="www.yogaflowsf.com">www.yogaflowsf.com</a> under Ocean events.'
  
schedule:
  -
    title: 'Yoga Flow SF Ocean'
    details: 'heated, 80 degrees'
    classes:
      -
        title: 'All Level Flow'
        time: 'Tues 6:30pm'
      -
        title: 'All Level Flow'
        time: 'Thurs 6:30pm'
      -
        title: 'All Level Flow'
        time: 'Fri 9:00am'
      -
        title: 'All Level Flow'
        time: 'Sat 9:00am'
  -
    title: 'Yoga Flow SF Union'
    details: 'heated, 80 degrees'
    classes:
      -
        title: 'All Level Flow'
        time: 'Sat 3:00 pm'
  -
    title: 'Yoga Tree Hayes Valley'
    classes:
      -
        title: 'Vinyasa All Levels'
        time: 'Tues 3:00pm'
      -
        title: 'Vinyasa All Levels'
        time: 'Thurs 3:00 pm'
  -
    title: 'Jewish Community Center of San Francisco '
    classes:
      -
        title: 'Intermediate Vinyasa'
        time: 'Tues 6:30 am'
      -
        title: 'Intermediate Vinyasa'
        time: 'Thurs 6:30 am'

carousel_images:
  - "assets/images/yellow_cap.jpg"
  - "assets/images/twist.jpg"
  - "assets/images/water.JPG"
  - "assets/images/aztec.jpg"
  - "assets/images/spider.jpg"


url: http://LaurenPisanoYoga.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: false

# if you don't have any of social below, comment the line
facebook: LaurenPisanoRD
instagram: laurenpisanoyoga
email: Lmpisano1@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"


# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: false

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
