# main text of home
name: Lauren Pisano Yoga
quote: 'You are an artist. If you practice yoga, you are an artist.'

bio: '<p>When we approach the practice as a creative expression, we are artists. We ignite the fire of creativity within ourselves and experience the teachings as they are; living, impermanent and ceaselessly transforming.</p>
<p>When we approach the practice as a discipline, we are held in the sacred tradition of yoga. We learn humility. We learn reverence. We learn what it means to be grounded.</p>
<p>My practice and therefore teaching is a dance around this balance point between discipline and artistry. I offer what wisdom has been revealed to me in my journey as it is natural and relevant to the moment I share with you in the yoga room. Vinyasa classes are alive, flowing, grounded and deliberate. Yin and restorative classes are healing, meditative and quiet.</p>
<p>Adi Vajra and Stephanie Adams showed me what yoga is. My teaching is a tree grown in their soil.</p>
<p>Join or connect with me as it serves you. All are welcome. It is not important that you are perfect, only that you are sincere.</p>
<p>Yours truly, eternally in bloom,<br>
Lauren</p>'

# if it's an external image, update below for true
external-image: false
picture: 'assets/images/lauren_headshot.jpg'

events:
  -
    title: 'Downtempo Flow with Lauren Pisano and DJ Flashflooder'
    date: 'Nov 17, 2016 630pm-755pm at Yoga Flow SF Ocean'
    description: 'Join Lauren Pisano and DJ Flashflooder for a flow yoga class set to a backdrop of hand-selected downtempo, ambient and experimental music.<br><br> A little more about DJ Flashflooder: Christopher Lim is a bay area based DJ best known for his eclectic tastes and mixing style which provides him the flexibility to navigate the dance floor, the lounge, or the yoga studio with ease. Having always been a champion of downtempo, ambient, and experimental music, performing alongside yogis comes naturally to him and is exemplified by his ability to assist the students in getting lost in the art of yoga and music, offering a brief escape from the trappings of every day life. Music is his #1 passion and this comes through clearly in his past contributions to KALX Berkeley and DJ Techtools, his involvement in the Zero Fucks’ crew’s events such as the monthly House of Bass show, and from his popular podcast A State of Trap. <br><br> <a href="www.yogaflowsf.com">www.yogaflowsf.com</a>'  
  -
    title: 'Diving Deeper: 15-hour Weekend Yoga Intensive with Lauren Pisano'
    date: 'January 20-22, 2016'
    description: >
      Spend a weekend diving deeper into the practice of yoga
      with Lauren and a small group of yogis.<br>
      We will intimately discuss yoga philosophy, break down common yoga poses, learn the meanings of
      mantras and practice chanting together. This urban retreat is an opportunity to deepen your yoga
      practice, have fun, connect and heal.<br><br>
      Schedule:<br>
      Friday Jan 20th: 6:00pm -8:30pm at YFSF Ocean<br>
      Saturday Jan 21st: 9am -10:30am Practice with Lauren at YFSF Ocean. 12:30pm -6:30pm at YFSF Ocean.<br>
      Sunday Jan 22nd: 1:00pm -6:30pm at YFSF Ocean.<br>



schedule:
  -
    title: 'Yoga Flow SF Ocean'
    details: 'heated, 80 degrees'
    classes:
      -
        title: 'All Level Flow'
        time: 'Tues 6:30pm'
      -
        title: 'All Level Flow'
        time: 'Thurs 6:30pm'
      -
        title: 'All Level Flow'
        time: 'Fri 9:00am'
      -
        title: 'All Level Flow'
        time: 'Sat 9:00am'
  -
    # title: 'Yoga Flow SF Union'
    # details: 'heated, 80 degrees'
    # classes:
      -
        # title: 'All Level Flow'
        # time: 'Sat 3:00 pm'
  -
    title: 'Yoga Tree Castro'
    classes:
      -
        title: 'Vinyasa All Levels'
        time: 'Tues 3:00pm'
      -
        title: 'Vinyasa All Levels'
        time: 'Thurs 3:00 pm'
  -
    title: 'Jewish Community Center of San Francisco '
    classes:
      -
        title: 'Intermediate Vinyasa'
        time: 'Tues 6:30 am'
      -
        title: 'Intermediate Vinyasa'
        time: 'Thurs 6:30 am'

carousel_images:
  - "assets/images/yellow_cap.jpg"
  - "assets/images/twist.jpg"
  - "assets/images/water.JPG"
  - "assets/images/lauren-dance.jpg"
  - "assets/images/spider.jpg"


url: http://LaurenPisanoYoga.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: false

# if you don't have any of social below, comment the line
facebook: LaurenPisanoyoga
instagram: laurenpisanoyoga
email: Lmpisano1@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"


# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: false

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
